### ISSUE TITLE
Too much empty Space

### ISSUE THREAD

**Issue by MatthewLangisholdingmehostage** [Mathmagician8191/Calculus-Questions#11]
Can you add a picture of yourself to fill the white space. I hope it looks like this.
![Untitled-1](https://user-images.githubusercontent.com/54007761/62840118-81a53300-bce9-11e9-8c3b-450e0bdb3428.jpg)

**Comment by Mathmagician8191** [comment]
How about you suggest a more useful use of the space?

**Comment by MatthewLangisholdingmehostage** [comment]
How am I supposed to have fun with Calculus if I can't see how much Fun you're having.

**Comment by Mathmagician8191** [comment]
The space has been used by the function reference
