### ISSUE TITLE
A useful way to fill the Empty space.

### ISSUE THREAD

**Issue by MatthewLangisholdingmehostage** [Mathmagician8191/Calculus-Questions#15]
![Untitled-2](https://user-images.githubusercontent.com/54007761/62986195-78090000-be8e-11e9-9b0f-980db0b638b5.png)

I feel like you should fill the empty space with these images depending on if you get the question correct or incorrect. This would provide good feedback to the user when they get the question right or wrong, as now it is a small message. (The Images should be of your face, This was just an artist's depiction of what they should look like. However, if you want to use my Images I might give you permission to use them if you really ask nicely.)

**Comment by MatthewLangisholdingmehostage** [comment]
Not a duplicate noob.

I bet you mine Diamonds with a wooden Pickaxe.

**Comment by MatthewLangisholdingmehostage** [comment]
I love you Matthew

**Comment by Mathmagician8191** [comment]
The background colour has already been taken by difficulty

**Comment by MATTHEWmadeMEdoTHIS** [comment]
I think you should fill the empty space with maybe a design or a list of helpful equations and formulas

**Comment by Mathmagician8191** [comment]
The function reference has been moved to the main page, which uses the space
