### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by MatthewLangisholdingmehostage** [Mathmagician8191/Calculus-Questions#23]
Are you gonna include anything on integration/Anti-Differentiation. 
This would be helpful. 
![download](https://user-images.githubusercontent.com/54007761/63729020-e780e580-c8b9-11e9-98b6-77372e0515c8.jpg)

**Comment by Mathmagician8191** [comment]
One problem is that the simplification could fail to account for the constant, e.g. tan(x)^2+c is valid if 1/cos(x)^2+c is the correct answer because tan(x)^2+1 = 1/cos(x)^2 and the constant can account for the difference
