### ISSUE TITLE
Making the Function Box stand out more 

### ISSUE THREAD

**Issue by MatthewLangisholdingmehostage** [Mathmagician8191/Calculus-Questions#24]
I think that you could put the whole function reference thing in a different coloured Box as currently it falls into the background and doesn't stand out much.

Also adding an explanation in words to each of the Functions listed could be beneficial to the Function Reference Table (They could be Hidden Tabs like other websites have or something.)

**Comment by MatthewLangisholdingmehostage** [comment]
![Conclusion](https://user-images.githubusercontent.com/54007761/63905634-f3f77080-ca68-11e9-9f50-3e2c468564f9.PNG)

**Comment by Mathmagician8191** [comment]
Have you got a suggested colour?

**Comment by MatthewLangisholdingmehostage** [comment]
I would suggest a colour like C55BE5 or something similar. 
Like the colour of the Purpur blocks
