### ISSUE TITLE
Counter for correct/incorrect questions

### ISSUE THREAD

**Issue by I-Love-Hentai** [Mathmagician8191/Calculus-Questions#28]
Make a counter to show how many questions you have gotten correct / incorrect :)

**Comment by Mathmagician8191** [comment]
Should it reset when you change difficulty or when you get a question wrong?

**Comment by I-Love-Hentai** [comment]
> Should it reset when you change difficulty or when you get a question wrong?

it should reset if you change difficulty. maybe have an option to set a question limit and so you get a score counter of correct questions / total questions
