### ISSUE TITLE
A thing that tells you the Highest streak you have

### ISSUE THREAD

**Issue by MatthewLangisholdingmehostage** [Mathmagician8191/Calculus-Questions#39]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MatthewLangisholdingmehostage** [comment]
I forgot to remoev the thing

**Comment by MatthewLangisholdingmehostage** [comment]
to remove the thing

**Comment by Mathmagician8191** [comment]
Should the highest streak be reset when you change difficulty, should there be highest streaks for each difficulty or just a highest streak in general?
Also, should the streak be saved as a cookie?

**Comment by MatthewLangisholdingmehostage** [comment]
Streaks should remain regardless of difficulty. 
I would also like cookies for high streaks.

**Comment by MatthewLangisholdingmehostage** [comment]
WHat kind of cookies

**Comment by MatthewLangisholdingmehostage** [comment]
what

**Comment by MatthewLangisholdingmehostage** [comment]
type of

**Comment by MatthewLangisholdingmehostage** [comment]
cookies

**Comment by Mathmagician8191** [comment]
Javascript cookies

**Comment by MatthewLangisholdingmehostage** [comment]
yim yum

**Comment by Mathmagician8191** [comment]
I might use localStorage instead
