### ISSUE TITLE
Place to learn

### ISSUE THREAD

**Issue by MathmagicianTheMatthew** [Mathmagician8191/Calculus-Questions#9]
Another issue is that I believe that there should be a place to learn firstly and then get these questions.

**Comment by Mathmagician8191** [comment]
This tool is meant for revision, so the place to learn is not needed. What would you suggest a place to lean should have?

**Comment by MatthewLangisholdingmehostage** [comment]
I believe there should be a page that lists all the different functions as well as giving examples of how to do it. This should be included because if someone forgets how to do a problem or encounters one they don't know how to do they can figure it out.
